### ISSUE TITLE
Nombres de microservicios irregulares

### ISSUE THREAD

**Issue by Billones142** [gmartineza/bienal-backend#10]
En la rama de cada modulo tienen que ponerse de acuerdo como van a nombrar los nombre de las carpetas, porque por ejemplo en el modulo de gestion se divide en servicios, en el de votYVal se dividen en submodulos, y el de visualizacion ni siquiera esta en su propia carpeta.

Asi que cada uno tendria que corregir en su rama eso y despues hacer un PR a development

**Comment by gmartineza** [comment]
@Billones142 porfa revisá el merge #13 y cerrá este issue si corresponde

**Comment by Billones142** [comment]
Me parece correcto el cambio, cierro el issue.
