### ISSUE TITLE
Modulo de visualizacion?

### ISSUE THREAD

**Issue by Billones142** [gmartineza/bienal-backend#14]
Veo que en la raíz del proyecto hay tres directorios que empiezan con "visualizacion".
![issueDeVisualizacion](https://github.com/user-attachments/assets/75ae43b3-3075-4db9-9ea1-28734a7c4c14)
¿No seria mejor juntar todos estos para que sea solo un modulo?
@gmartineza @PaulinaPalmeyro

**Comment by gmartineza** [comment]
En que rama es eso?

**Comment by gmartineza** [comment]
Se habló y definió que las funcionalidades de visualización iban a implementarse en el módulo de gestión porque son muy simples para considerarlas un módulo entero a parte. Cierro porque esos directorios están obsoletos.
